### ISSUE TITLE
IR passes to implement

### ISSUE THREAD

**Issue by rachitnigam** [cucapra/filament#200]
The old compiler flow has a bunch of different passes that need to be transitioned before we replace it with the IR:
- [x] Add assumptions
- [x] Type check
- [x] Interval check
- [ ] Sharing check: Enforce the sharing check for reused instances (#109)
- [x] Phantom check
- [x] Use/def reordering (enforce domination #245)
- [x] Monomorphize
- [x] Bundle elimination: Remove bundles from component signatures
- [x] Lower
- [x] Compile to Calyx

**Comment by rachitnigam** [comment]
Not sure if I've mentioned this before but the following command will print out the program AST after each pass in the existing compiler flow:
```
cargo run -- <file> --log debug
```

Use this to check whether a particular pass generates the right kind of code

**Comment by gabizon103** [comment]
This was accidentally closed when `ir-dev` got merged into `main`, but the sharing check still isn't implemented so I'm reopening until that's done
