### ISSUE TITLE
Components to implement

### ISSUE THREAD

**Issue by rachitnigam** [cucapra/filament#33]
Some components we should implement:
- [ ] Sequential read/write memories
- [x] Iterative Divider
- [x] Pipelined divider (do these exist?)
- [ ] Square root (for polybench benchmarks)
