### ISSUE TITLE
Cleanup deadline code

### ISSUE THREAD

**Issue by rachitnigam** [cucapra/filament#405]
#398 has a bunch of code that was written during a deadline and needs to be cleaned up.

- [ ] Adds XLS as a `gen` tool (separate branch).
- [ ] Adds XLS to the Dockerfile (new issue b/c the problem is that `bazel` only seems to work on x86. We need to install the `arm64` version based on the build)
- [ ] Adds the various FFT implementation (only the pure Filament implementation should be in the repo. Others should go in the evaluation repo)
- [ ] Uses `verible` to rename the modules generated by `flopoco` so they don't clash (separate branch, @UnsignedByte will create an issue)
  - Current, this just does random name mangling using `verible`. Maybe `slang` is a better option?
- [ ] It adds a primitive to merge values to the same wire (@UnsignedByte can you make an issue describing exactly what this is?)
  - Can this be implemented purely in Filament?
- [ ] Adds a way to specify global values used in a `gen` configuration (open an issue to discuss the current implementation)
  - This seems like a generally useful mechanism but we need to be careful because it might pollute names defined by each tool
