### ISSUE TITLE
HLS Filament: Tracker

### ISSUE THREAD

**Issue by UnsignedByte** [cucapra/filament#457]
For the HLS Filament features described in #454, here is a possible plan of attack:
- [ ] #455 
- [ ] #456 
- [ ] Timing model (hardcoded?)
- [ ] ASAP Scheduling implementation using physical IR
- [ ] SDC Module scheduling
- [ ] FDO
